packages:
  - "."

minimumReleaseAge: 21600

overrides:
  esbuild: 0.25.0
  fast-uri: 3.1.6

allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@sentry/cli': true
  '@swc/core': true
  cpu-features: true
  esbuild: true
  prisma: true
  sharp: true
  ssh2: true
