import path from 'node:path'
import { defineConfig } from 'vitest/config'

const srcDir = path.resolve(__dirname, 'src')

export default defineConfig({
  resolve: {
    alias: {
      '~': srcDir,
    },
  },
  test: {
    projects: [
      {
        resolve: {
          alias: {
            'server-only': path.resolve(srcDir, '__tests__/helpers/server-only-stub.ts'),
            '~': srcDir,
          },
        },
        test: {
          name: 'unit',
          include: ['src/**/*.test.ts', 'cli/**/*.test.ts'],
          exclude: ['src/**/*.integration.test.ts', 'cli/**/*.integration.test.ts', 'cli/commands/audit-rgaa/**/*.test.ts'],
          env: {
            BASE_URL: 'http://localhost:3000',
            SENTRY_CSP_REPORT_URI: 'https://sentry.example.com/api/1/security/?sentry_key=test',
            AUTH_SECRET: 'test-secret',
            DATABASE_URL: 'postgres://test:test@localhost:5432/test',
            BREVO_API_KEY: 'test-brevo-key',

            BREVO_TEMPLATE_MAGIC_LINK: '1',
            BREVO_TEMPLATE_VALIDATION: '1',
            BREVO_TEMPLATE_RESET_PASSWORD: '1',
            BREVO_TEMPLATE_OWNER_WELCOME: '1',
            BREVO_TEMPLATE_ADMIN_RESET_PASSWORD: '1',
            BREVO_TEMPLATE_STUDENT_ALERT: '1',
            BREVO_TEMPLATE_ALERT_CREATION: '43',
            BREVO_TEMPLATE_ALERT_EXPIRY_REMINDER: '46',
            BREVO_TEMPLATE_ALERT_DEACTIVATION: '48',
            BREVO_TEMPLATE_CONTACT_CONFIRMATION: '58',
            BREVO_TEMPLATE_APPLICATIONS_MANAGEMENT_GRANTED: '59',
            BREVO_TEMPLATE_APPLICATIONS_SUSPENDED: '60',
            BREVO_CONTACTS_API_URL: 'https://api.brevo.com/v3/contacts',
            WP_FAQ_URL: 'https://info.monlogementetudiant.beta.gouv.fr',
            WP_FAQ_PAGE_ID: '1774',
            API_V1_ENABLED: 'true',
            API_V1_RATE_LIMIT_MAX: '120',
            API_V1_RATE_LIMIT_WINDOW_MS: '60000',
            S3_ENDPOINT: 'https://s3.example.com',
            S3_BUCKET: 'test-bucket',
            S3_ACCESS_KEY_ID: 'test-key-id',
            S3_SECRET_ACCESS_KEY: 'test-secret-key',
            S3_BACKUP_BUCKET: 'test-backup-bucket',
            MATOMO_URL: 'https://matomo.example.com/',
            MATOMO_TOKEN: 'test-token',
            MATOMO_ID_SITE: '1',
            RAMSESE_API_URL: 'https://ramsese.example.com/ramsese-webservice',
            RAMSESE_CODE_APPLICATION: '00',
            RAMSESE_API_KEY: 'test-ramsese-key',
          },
        },
      },
      {
        resolve: {
          alias: [
            { find: 'server-only', replacement: path.resolve(srcDir, '__tests__/helpers/server-only-stub.ts') },
            { find: /^~\/server\/db$/, replacement: path.resolve(srcDir, '__tests__/helpers/test-db-module.ts') },
            { find: '~', replacement: srcDir },
          ],
        },
        test: {
          name: 'integration',
          include: ['src/**/*.integration.test.ts', 'cli/**/*.integration.test.ts'],
          testTimeout: 30_000,
          hookTimeout: 60_000,
          setupFiles: ['src/__tests__/helpers/setup-integration.ts'],
          fileParallelism: false,
          env: {
            BASE_URL: 'http://localhost:3000',
            SENTRY_CSP_REPORT_URI: 'https://sentry.example.com/api/1/security/?sentry_key=test',
            AUTH_SECRET: 'test-secret-for-integration-tests',
            DATABASE_URL: 'postgres://test:test@localhost:5491/mle_test',
            BREVO_API_KEY: 'test-brevo-api-key',

            BREVO_TEMPLATE_MAGIC_LINK: '1',
            BREVO_TEMPLATE_VALIDATION: '1',
            BREVO_TEMPLATE_RESET_PASSWORD: '1',
            BREVO_TEMPLATE_OWNER_WELCOME: '1',
            BREVO_TEMPLATE_ADMIN_RESET_PASSWORD: '1',
            BREVO_TEMPLATE_STUDENT_ALERT: '1',
            BREVO_TEMPLATE_ALERT_CREATION: '43',
            BREVO_TEMPLATE_ALERT_EXPIRY_REMINDER: '46',
            BREVO_TEMPLATE_ALERT_DEACTIVATION: '48',
            BREVO_TEMPLATE_CONTACT_CONFIRMATION: '58',
            BREVO_TEMPLATE_APPLICATIONS_MANAGEMENT_GRANTED: '59',
            BREVO_TEMPLATE_APPLICATIONS_SUSPENDED: '60',
            BREVO_CONTACTS_API_URL: 'https://api.brevo.com/v3/contacts',
            WP_FAQ_URL: 'https://info.monlogementetudiant.beta.gouv.fr',
            WP_FAQ_PAGE_ID: '1774',
            API_V1_ENABLED: 'true',
            API_V1_RATE_LIMIT_MAX: '120',
            API_V1_RATE_LIMIT_WINDOW_MS: '60000',
            S3_ENDPOINT: 'https://s3.example.com',
            S3_BUCKET: 'test-bucket',
            S3_ACCESS_KEY_ID: 'test-key-id',
            S3_SECRET_ACCESS_KEY: 'test-secret-key',
            S3_BACKUP_BUCKET: 'test-backup-bucket',
            MATOMO_URL: 'https://matomo.example.com/',
            MATOMO_TOKEN: 'test-token',
            MATOMO_ID_SITE: '1',
            IBAIL_API_HOST: 'https://ibail.example.com',
            IBAIL_API_AUTH_KEY: 'test-key',
            IBAIL_API_AUTH_SECRET: 'test-secret',
          },
        },
      },
    ],
  },
})
