-- Extensions
CREATE EXTENSION IF NOT EXISTS unaccent;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS postgis;

CREATE OR REPLACE FUNCTION immutable_unaccent(text)
RETURNS text AS $$ SELECT unaccent($1) $$ LANGUAGE sql IMMUTABLE PARALLEL SAFE;

-- Territories
CREATE TABLE IF NOT EXISTS "territories_academy" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "territories_academy_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(200) NOT NULL,
	"boundary" geometry(multipolygon, 4326)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "territories_department" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "territories_department_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(200) NOT NULL,
	"code" varchar(3) NOT NULL,
	"boundary" geometry(multipolygon, 4326),
	"academy_id" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "territories_city" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "territories_city_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(200) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"postal_codes" varchar(5)[] NOT NULL,
	"insee_codes" varchar(5)[] NOT NULL,
	"epci_code" varchar(9),
	"boundary" geometry(multipolygon, 4326),
	"department_id" bigint NOT NULL,
	"popular" boolean NOT NULL,
	"population" integer,
	"average_income" double precision,
	"nb_students" integer,
	"average_rent" double precision
);
--> statement-breakpoint
-- Owners
CREATE TABLE IF NOT EXISTS "account_owner" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "account_owner_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(200) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"url" varchar(500),
	"image" bytea,
	CONSTRAINT "account_owner_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
-- Better Auth tables
CREATE TABLE IF NOT EXISTS "user" (
	"id" text PRIMARY KEY NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean DEFAULT false NOT NULL,
	"name" text NOT NULL,
	"image" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"firstname" text DEFAULT '' NOT NULL,
	"lastname" text DEFAULT '' NOT NULL,
	"role" text DEFAULT 'user' NOT NULL,
	"legacy_user" boolean DEFAULT false NOT NULL,
	"legacy_id" integer,
	"owner_id" bigint,
	CONSTRAINT "user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "account" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"access_token_expires_at" timestamp with time zone,
	"refresh_token_expires_at" timestamp with time zone,
	"scope" text,
	"id_token" text,
	"password" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "session" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"token" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
-- Accommodations
CREATE TABLE IF NOT EXISTS "accommodation_accommodation" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "accommodation_accommodation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(200) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"description" text,
	"address" varchar(255),
	"city" varchar(150) NOT NULL,
	"postal_code" varchar(5) NOT NULL,
	"residence_type" varchar(100),
	"target_audience" varchar(100),
	"published" boolean NOT NULL,
	"available" boolean NOT NULL,
	"geom" geometry(point, 4326),
	"nb_total_apartments" integer,
	"nb_accessible_apartments" integer,
	"nb_coliving_apartments" integer,
	"nb_t1" integer,
	"nb_t1_bis" integer,
	"nb_t2" integer,
	"nb_t3" integer,
	"nb_t4" integer,
	"nb_t5" integer,
	"nb_t6" integer,
	"nb_t7_more" integer,
	"nb_t1_available" integer,
	"nb_t1_bis_available" integer,
	"nb_t2_available" integer,
	"nb_t3_available" integer,
	"nb_t4_available" integer,
	"nb_t5_available" integer,
	"nb_t6_available" integer,
	"nb_t7_more_available" integer,
	"price_min" integer,
	"price_min_t1" integer,
	"price_max_t1" integer,
	"price_min_t1_bis" integer,
	"price_max_t1_bis" integer,
	"price_min_t2" integer,
	"price_max_t2" integer,
	"price_min_t3" integer,
	"price_max_t3" integer,
	"price_min_t4" integer,
	"price_max_t4" integer,
	"price_min_t5" integer,
	"price_max_t5" integer,
	"price_min_t6" integer,
	"price_max_t6" integer,
	"price_min_t7_more" integer,
	"price_max_t7_more" integer,
	"laundry_room" boolean,
	"common_areas" boolean,
	"bike_storage" boolean,
	"parking" boolean,
	"secure_access" boolean,
	"residence_manager" boolean,
	"kitchen_type" varchar(50),
	"desk" boolean,
	"cooking_plates" boolean,
	"microwave" boolean,
	"refrigerator" boolean,
	"wifi" boolean,
	"bathroom" varchar(50),
	"accept_waiting_list" boolean,
	"scholarship_holders_priority" boolean,
	"images_urls" text[],
	"images_count" integer NOT NULL,
	"external_url" varchar(255),
	"external_reference" varchar(255),
	"owner_id" bigint,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "accommodation_externalsource" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "accommodation_externalsource_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"accommodation_id" bigint NOT NULL,
	"source" varchar(100) DEFAULT 'clef' NOT NULL,
	"source_id" varchar(100),
	CONSTRAINT "accommodation_externalsource_source_accommodation_id_unique" UNIQUE("source","accommodation_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "accommodation_favoriteaccommodation" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "accommodation_favoriteaccommodation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" varchar(255) NOT NULL,
	"accommodation_id" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "accommodation_favoriteaccommodation_user_id_accommodation_id_unique" UNIQUE("user_id","accommodation_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "newsletter_subscription" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "newsletter_subscription_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"email" varchar(255) NOT NULL,
	"payload" jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "faq_question_answer" (
	"id" bigint PRIMARY KEY NOT NULL,
	"title_fr" varchar(500) NOT NULL,
	"content_fr" text NOT NULL,
	"order" integer
);
--> statement-breakpoint
-- Stats
CREATE TABLE IF NOT EXISTS "stats_stats" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stats_stats_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"date" date NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"unique_visitors" integer,
	"new_visits_percentage" double precision,
	"average_duration" double precision,
	"bounce_rate_percentage" double precision,
	"page_views" integer,
	"visitors_per_page" double precision,
	"top_pages" jsonb,
	"main_entry_pages" jsonb,
	"main_sources" jsonb,
	CONSTRAINT "stats_stats_date_unique" UNIQUE("date")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "stats_eventstats" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stats_eventstats_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"date" date NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"category" varchar(255) NOT NULL,
	"action" varchar(255) NOT NULL,
	"nb_events" integer,
	"nb_unique_events" integer,
	"event_value" double precision
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "student_alert" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "student_alert_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"city_id" bigint,
	"department_id" bigint,
	"academy_id" bigint,
	"has_coliving" boolean DEFAULT false NOT NULL,
	"is_accessible" boolean DEFAULT false NOT NULL,
	"max_price" integer NOT NULL,
	"receive_notifications" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
-- Idempotent columns for backup import (tables may exist from Django)
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "firstname" text DEFAULT '' NOT NULL;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "lastname" text DEFAULT '' NOT NULL;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "role" text DEFAULT 'user' NOT NULL;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "legacy_user" boolean DEFAULT false NOT NULL;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "legacy_id" integer;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "owner_id" bigint;
--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "description" text;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "address" varchar(255);
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "residence_type" varchar(100);
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "target_audience" varchar(100);
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "nb_accessible_apartments" integer;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "nb_coliving_apartments" integer;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "nb_t1_available" integer;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "nb_t1_bis_available" integer;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "nb_t2_available" integer;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "nb_t3_available" integer;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "nb_t4_available" integer;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "nb_t5_available" integer;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "nb_t6_available" integer;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "nb_t7_more_available" integer;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "price_min_t1" integer;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "price_max_t1" integer;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "price_min_t1_bis" integer;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "price_max_t1_bis" integer;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "price_min_t2" integer;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "price_max_t2" integer;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "price_min_t3" integer;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "price_max_t3" integer;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "price_min_t4" integer;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "price_max_t4" integer;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "price_min_t5" integer;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "price_max_t5" integer;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "price_min_t6" integer;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "price_max_t6" integer;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "price_min_t7_more" integer;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "price_max_t7_more" integer;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "laundry_room" boolean;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "common_areas" boolean;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "bike_storage" boolean;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "parking" boolean;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "secure_access" boolean;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "residence_manager" boolean;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "kitchen_type" varchar(50);
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "desk" boolean;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "cooking_plates" boolean;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "microwave" boolean;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "refrigerator" boolean;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "wifi" boolean;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "bathroom" varchar(50);
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "accept_waiting_list" boolean;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "scholarship_holders_priority" boolean;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "images_urls" text[];
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "external_url" varchar(255);
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "external_reference" varchar(255);
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "owner_id" bigint;
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now();
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now();
--> statement-breakpoint
-- Migrate user_id from account_owner to user.owner_id (backup scenario)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'account_owner' AND column_name = 'user_id') THEN
    UPDATE "user" SET "owner_id" = ao."id" FROM "account_owner" ao WHERE ao."user_id" = "user"."id" AND "user"."owner_id" IS NULL;
    ALTER TABLE "account_owner" DROP COLUMN "user_id";
  END IF;
END $$;
--> statement-breakpoint
-- FK constraints (idempotent)
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'accommodation_accommodation_owner_id_account_owner_id_fk') THEN
    ALTER TABLE "accommodation_accommodation" ADD CONSTRAINT "accommodation_accommodation_owner_id_account_owner_id_fk" FOREIGN KEY ("owner_id") REFERENCES "public"."account_owner"("id") ON DELETE no action ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'account_user_id_user_id_fk') THEN
    ALTER TABLE "account" ADD CONSTRAINT "account_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'session_user_id_user_id_fk') THEN
    ALTER TABLE "session" ADD CONSTRAINT "session_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'territories_city_department_id_territories_department_id_fk') THEN
    ALTER TABLE "territories_city" ADD CONSTRAINT "territories_city_department_id_territories_department_id_fk" FOREIGN KEY ("department_id") REFERENCES "public"."territories_department"("id") ON DELETE no action ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'territories_department_academy_id_territories_academy_id_fk') THEN
    ALTER TABLE "territories_department" ADD CONSTRAINT "territories_department_academy_id_territories_academy_id_fk" FOREIGN KEY ("academy_id") REFERENCES "public"."territories_academy"("id") ON DELETE no action ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'accommodation_externalsource_accommodation_id_accommodation_accommodation_id_fk') THEN
    ALTER TABLE "accommodation_externalsource" ADD CONSTRAINT "accommodation_externalsource_accommodation_id_accommodation_accommodation_id_fk" FOREIGN KEY ("accommodation_id") REFERENCES "public"."accommodation_accommodation"("id") ON DELETE no action ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'accommodation_favoriteaccommodation_accommodation_id_accommodation_accommodation_id_fk') THEN
    ALTER TABLE "accommodation_favoriteaccommodation" ADD CONSTRAINT "accommodation_favoriteaccommodation_accommodation_id_accommodation_accommodation_id_fk" FOREIGN KEY ("accommodation_id") REFERENCES "public"."accommodation_accommodation"("id") ON DELETE no action ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'student_alert_city_id_territories_city_id_fk') THEN
    ALTER TABLE "student_alert" ADD CONSTRAINT "student_alert_city_id_territories_city_id_fk" FOREIGN KEY ("city_id") REFERENCES "public"."territories_city"("id") ON DELETE no action ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'student_alert_department_id_territories_department_id_fk') THEN
    ALTER TABLE "student_alert" ADD CONSTRAINT "student_alert_department_id_territories_department_id_fk" FOREIGN KEY ("department_id") REFERENCES "public"."territories_department"("id") ON DELETE no action ON UPDATE no action;
  END IF;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'student_alert_academy_id_territories_academy_id_fk') THEN
    ALTER TABLE "student_alert" ADD CONSTRAINT "student_alert_academy_id_territories_academy_id_fk" FOREIGN KEY ("academy_id") REFERENCES "public"."territories_academy"("id") ON DELETE no action ON UPDATE no action;
  END IF;
END $$;
