CREATE EXTENSION IF NOT EXISTS unaccent;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS postgis;

CREATE OR REPLACE FUNCTION immutable_unaccent(text)
RETURNS text AS $$ SELECT unaccent($1) $$ LANGUAGE sql IMMUTABLE PARALLEL SAFE;


CREATE TABLE IF NOT EXISTS "territories_academy" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "territories_academy_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(200) NOT NULL,
	"boundary" geometry(point)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "accommodation_accommodation" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "accommodation_accommodation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(200) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"city" varchar(150) NOT NULL,
	"postal_code" varchar(5) NOT NULL,
	"published" boolean NOT NULL,
	"available" boolean NOT NULL,
	"geom" geometry(point),
	"nb_total_apartments" integer,
	"nb_t1" integer,
	"nb_t1_bis" integer,
	"nb_t2" integer,
	"nb_t3" integer,
	"nb_t4" integer,
	"nb_t5" integer,
	"nb_t6" integer,
	"nb_t7_more" integer,
	"price_min" integer,
	"images_count" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "territories_city" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "territories_city_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(200) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"postal_codes" varchar(5)[] NOT NULL,
	"insee_codes" varchar(5)[] NOT NULL,
	"epci_code" varchar(9),
	"boundary" geometry(point),
	"department_id" bigint NOT NULL,
	"popular" boolean NOT NULL,
	"population" integer,
	"average_income" double precision,
	"nb_students" integer,
	"average_rent" double precision
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "territories_department" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "territories_department_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(200) NOT NULL,
	"code" varchar(3) NOT NULL,
	"boundary" geometry(point),
	"academy_id" bigint NOT NULL
);
--> statement-breakpoint
ALTER TABLE "territories_city" ADD CONSTRAINT "territories_city_department_id_territories_department_id_fk" FOREIGN KEY ("department_id") REFERENCES "public"."territories_department"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "territories_department" ADD CONSTRAINT "territories_department_academy_id_territories_academy_id_fk" FOREIGN KEY ("academy_id") REFERENCES "public"."territories_academy"("id") ON DELETE no action ON UPDATE no action;