-- Rename Q&A table if old name exists (must run before dropping django_content_type)
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'faq_questionanswer') THEN
    DELETE FROM "faq_questionanswer" WHERE content_type_id IS NOT NULL;
    ALTER TABLE "faq_questionanswer" DROP COLUMN IF EXISTS "content_type_id";
    ALTER TABLE "faq_questionanswer" DROP COLUMN IF EXISTS "object_id";
    ALTER TABLE "faq_questionanswer" RENAME TO "faq_question_answer";
  END IF;
END $$;
--> statement-breakpoint
-- Cleanup Django legacy tables
DROP TABLE IF EXISTS "auth_user_user_permissions" CASCADE;
DROP TABLE IF EXISTS "auth_user_groups" CASCADE;
DROP TABLE IF EXISTS "auth_group_permissions" CASCADE;
DROP TABLE IF EXISTS "auth_permission" CASCADE;
DROP TABLE IF EXISTS "auth_group" CASCADE;
DROP TABLE IF EXISTS "auth_identity" CASCADE;
DROP TABLE IF EXISTS "account_owner_users" CASCADE;
DROP TABLE IF EXISTS "account_student" CASCADE;
DROP TABLE IF EXISTS "account_studentregistrationtoken" CASCADE;
DROP TABLE IF EXISTS "auth_user" CASCADE;
DROP TABLE IF EXISTS "django_admin_log" CASCADE;
DROP TABLE IF EXISTS "django_session" CASCADE;
DROP TABLE IF EXISTS "django_migrations" CASCADE;
DROP TABLE IF EXISTS "django_content_type" CASCADE;
DROP TABLE IF EXISTS "django_summernote_attachment" CASCADE;
DROP TABLE IF EXISTS "token_blacklist_blacklistedtoken" CASCADE;
DROP TABLE IF EXISTS "token_blacklist_outstandingtoken" CASCADE;
DROP TABLE IF EXISTS "admin_two_factor_twofactorverification" CASCADE;
DROP TABLE IF EXISTS "accommodation_accommodationapplication" CASCADE;
DROP TABLE IF EXISTS "alerts_accommodationalert" CASCADE;
DROP TABLE IF EXISTS "dossier_facile_dossierfacileapplication" CASCADE;
DROP TABLE IF EXISTS "dossier_facile_dossierfacileoauthstate" CASCADE;
DROP TABLE IF EXISTS "dossier_facile_dossierfaciletenant" CASCADE;
DROP TABLE IF EXISTS "institution_educationalinstitution" CASCADE;
DROP TABLE IF EXISTS "qa_questionanswer" CASCADE;
DROP TABLE IF EXISTS "qa_questionanswerglobal" CASCADE;
DROP TABLE IF EXISTS "stats_accommodationchangelog" CASCADE;
DROP TABLE IF EXISTS "stats_gestionnaireloginevent" CASCADE;
DROP TABLE IF EXISTS "territories_country" CASCADE;
--> statement-breakpoint
-- Cleanup Metabase tables
DROP TABLE IF EXISTS "action" CASCADE;
DROP TABLE IF EXISTS "api_key" CASCADE;
DROP TABLE IF EXISTS "application_permissions_revision" CASCADE;
DROP TABLE IF EXISTS "audit_log" CASCADE;
DROP TABLE IF EXISTS "bookmark_ordering" CASCADE;
DROP TABLE IF EXISTS "cache_config" CASCADE;
DROP TABLE IF EXISTS "card_bookmark" CASCADE;
DROP TABLE IF EXISTS "card_label" CASCADE;
DROP TABLE IF EXISTS "channel" CASCADE;
DROP TABLE IF EXISTS "channel_template" CASCADE;
DROP TABLE IF EXISTS "cloud_migration" CASCADE;
DROP TABLE IF EXISTS "collection" CASCADE;
DROP TABLE IF EXISTS "collection_bookmark" CASCADE;
DROP TABLE IF EXISTS "collection_permission_graph_revision" CASCADE;
DROP TABLE IF EXISTS "comment" CASCADE;
DROP TABLE IF EXISTS "comment_reaction" CASCADE;
DROP TABLE IF EXISTS "connection_impersonations" CASCADE;
DROP TABLE IF EXISTS "content_translation" CASCADE;
DROP TABLE IF EXISTS "core_session" CASCADE;
DROP TABLE IF EXISTS "core_user" CASCADE;
DROP TABLE IF EXISTS "dashboard_bookmark" CASCADE;
DROP TABLE IF EXISTS "dashboard_favorite" CASCADE;
DROP TABLE IF EXISTS "dashboard_tab" CASCADE;
DROP TABLE IF EXISTS "dashboardcard_series" CASCADE;
DROP TABLE IF EXISTS "data_edit_undo_chain" CASCADE;
DROP TABLE IF EXISTS "data_permissions" CASCADE;
DROP TABLE IF EXISTS "databasechangelog" CASCADE;
DROP TABLE IF EXISTS "databasechangeloglock" CASCADE;
DROP TABLE IF EXISTS "db_router" CASCADE;
DROP TABLE IF EXISTS "dependency" CASCADE;
DROP TABLE IF EXISTS "dimension" CASCADE;
DROP TABLE IF EXISTS "document" CASCADE;
DROP TABLE IF EXISTS "document_bookmark" CASCADE;
DROP TABLE IF EXISTS "field_usage" CASCADE;
DROP TABLE IF EXISTS "glossary" CASCADE;
DROP TABLE IF EXISTS "http_action" CASCADE;
DROP TABLE IF EXISTS "implicit_action" CASCADE;
DROP TABLE IF EXISTS "label" CASCADE;
DROP TABLE IF EXISTS "login_history" CASCADE;
DROP TABLE IF EXISTS "metabase_cluster_lock" CASCADE;
DROP TABLE IF EXISTS "metabase_database" CASCADE;
DROP TABLE IF EXISTS "metabase_field" CASCADE;
DROP TABLE IF EXISTS "metabase_field_user_settings" CASCADE;
DROP TABLE IF EXISTS "metabase_fieldvalues" CASCADE;
DROP TABLE IF EXISTS "metabase_table" CASCADE;
DROP TABLE IF EXISTS "metabot" CASCADE;
DROP TABLE IF EXISTS "metabot_conversation" CASCADE;
DROP TABLE IF EXISTS "metabot_message" CASCADE;
DROP TABLE IF EXISTS "metabot_prompt" CASCADE;
DROP TABLE IF EXISTS "metric" CASCADE;
DROP TABLE IF EXISTS "metric_important_field" CASCADE;
DROP TABLE IF EXISTS "model_index" CASCADE;
DROP TABLE IF EXISTS "model_index_value" CASCADE;
DROP TABLE IF EXISTS "moderation_review" CASCADE;
DROP TABLE IF EXISTS "native_query_snippet" CASCADE;
DROP TABLE IF EXISTS "notification" CASCADE;
DROP TABLE IF EXISTS "notification_card" CASCADE;
DROP TABLE IF EXISTS "notification_handler" CASCADE;
DROP TABLE IF EXISTS "notification_recipient" CASCADE;
DROP TABLE IF EXISTS "notification_subscription" CASCADE;
DROP TABLE IF EXISTS "parameter_card" CASCADE;
DROP TABLE IF EXISTS "permissions" CASCADE;
DROP TABLE IF EXISTS "permissions_group" CASCADE;
DROP TABLE IF EXISTS "permissions_group_membership" CASCADE;
DROP TABLE IF EXISTS "permissions_revision" CASCADE;
DROP TABLE IF EXISTS "persisted_info" CASCADE;
DROP TABLE IF EXISTS "pulse" CASCADE;
DROP TABLE IF EXISTS "pulse_card" CASCADE;
DROP TABLE IF EXISTS "pulse_channel" CASCADE;
DROP TABLE IF EXISTS "pulse_channel_recipient" CASCADE;
DROP TABLE IF EXISTS "python_library" CASCADE;
DROP TABLE IF EXISTS "qrtz_blob_triggers" CASCADE;
DROP TABLE IF EXISTS "qrtz_calendars" CASCADE;
DROP TABLE IF EXISTS "qrtz_cron_triggers" CASCADE;
DROP TABLE IF EXISTS "qrtz_fired_triggers" CASCADE;
DROP TABLE IF EXISTS "qrtz_job_details" CASCADE;
DROP TABLE IF EXISTS "qrtz_locks" CASCADE;
DROP TABLE IF EXISTS "qrtz_paused_trigger_grps" CASCADE;
DROP TABLE IF EXISTS "qrtz_scheduler_state" CASCADE;
DROP TABLE IF EXISTS "qrtz_simple_triggers" CASCADE;
DROP TABLE IF EXISTS "qrtz_simprop_triggers" CASCADE;
DROP TABLE IF EXISTS "qrtz_triggers" CASCADE;
DROP TABLE IF EXISTS "query" CASCADE;
DROP TABLE IF EXISTS "query_action" CASCADE;
DROP TABLE IF EXISTS "query_cache" CASCADE;
DROP TABLE IF EXISTS "query_execution" CASCADE;
DROP TABLE IF EXISTS "query_field" CASCADE;
DROP TABLE IF EXISTS "query_table" CASCADE;
DROP TABLE IF EXISTS "recent_views" CASCADE;
DROP TABLE IF EXISTS "remote_sync_object" CASCADE;
DROP TABLE IF EXISTS "remote_sync_task" CASCADE;
DROP TABLE IF EXISTS "report_card" CASCADE;
DROP TABLE IF EXISTS "report_cardfavorite" CASCADE;
DROP TABLE IF EXISTS "report_dashboard" CASCADE;
DROP TABLE IF EXISTS "report_dashboardcard" CASCADE;
DROP TABLE IF EXISTS "revision" CASCADE;
DROP TABLE IF EXISTS "sandboxes" CASCADE;
DROP TABLE IF EXISTS "search_index_metadata" CASCADE;
DROP TABLE IF EXISTS "secret" CASCADE;
DROP TABLE IF EXISTS "segment" CASCADE;
DROP TABLE IF EXISTS "semantic_search_token_tracking" CASCADE;
DROP TABLE IF EXISTS "sequences" CASCADE;
DROP TABLE IF EXISTS "setting" CASCADE;
DROP TABLE IF EXISTS "support_access_grant_log" CASCADE;
DROP TABLE IF EXISTS "table_privileges" CASCADE;
DROP TABLE IF EXISTS "task_history" CASCADE;
DROP TABLE IF EXISTS "tenant" CASCADE;
DROP TABLE IF EXISTS "timeline" CASCADE;
DROP TABLE IF EXISTS "timeline_event" CASCADE;
DROP TABLE IF EXISTS "transform" CASCADE;
DROP TABLE IF EXISTS "transform_job" CASCADE;
DROP TABLE IF EXISTS "transform_job_run" CASCADE;
DROP TABLE IF EXISTS "transform_job_transform_tag" CASCADE;
DROP TABLE IF EXISTS "transform_run" CASCADE;
DROP TABLE IF EXISTS "transform_run_cancelation" CASCADE;
DROP TABLE IF EXISTS "transform_tag" CASCADE;
DROP TABLE IF EXISTS "transform_transform_tag" CASCADE;
DROP TABLE IF EXISTS "user_key_value" CASCADE;
DROP TABLE IF EXISTS "user_parameter_value" CASCADE;
DROP TABLE IF EXISTS "view_log" CASCADE;
--> statement-breakpoint
-- Cleanup Metabase search index tables (dynamic names)
DO $$ DECLARE
  r RECORD;
BEGIN
  FOR r IN SELECT tablename FROM pg_tables WHERE schemaname = 'public' AND tablename LIKE 'search_index__%' LOOP
    EXECUTE 'DROP TABLE IF EXISTS "' || r.tablename || '" CASCADE';
  END LOOP;
END $$;
