CREATE TABLE IF NOT EXISTS "accommodation_externalsource" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "accommodation_externalsource_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"accommodation_id" bigint NOT NULL,
	"source" varchar(100) DEFAULT 'clef' NOT NULL,
	"source_id" varchar(100),
	CONSTRAINT "accommodation_externalsource_source_accommodation_id_unique" UNIQUE("source","accommodation_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "accommodation_favoriteaccommodation" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "accommodation_favoriteaccommodation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" varchar(255) NOT NULL,
	"accommodation_id" bigint NOT NULL,
	"created_at" timestamp DEFAULT now(),
	CONSTRAINT "accommodation_favoriteaccommodation_user_id_accommodation_id_unique" UNIQUE("user_id","accommodation_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "account_owner" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "account_owner_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(200) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"url" varchar(500),
	CONSTRAINT "account_owner_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "description" text;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "address" varchar(255);--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "residence_type" varchar(100);--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "nb_accessible_apartments" integer;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "nb_coliving_apartments" integer;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "nb_t1_available" integer;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "nb_t1_bis_available" integer;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "nb_t2_available" integer;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "nb_t3_available" integer;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "nb_t4_available" integer;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "nb_t5_available" integer;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "nb_t6_available" integer;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "nb_t7_more_available" integer;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "price_min_t1" integer;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "price_max_t1" integer;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "price_min_t1_bis" integer;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "price_max_t1_bis" integer;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "price_min_t2" integer;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "price_max_t2" integer;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "price_min_t3" integer;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "price_max_t3" integer;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "price_min_t4" integer;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "price_max_t4" integer;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "price_min_t5" integer;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "price_max_t5" integer;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "price_min_t6" integer;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "price_max_t6" integer;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "price_min_t7_more" integer;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "price_max_t7_more" integer;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "laundry_room" boolean;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "common_areas" boolean;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "bike_storage" boolean;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "parking" boolean;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "secure_access" boolean;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "residence_manager" boolean;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "kitchen_type" varchar(50);--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "desk" boolean;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "cooking_plates" boolean;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "microwave" boolean;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "refrigerator" boolean;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "wifi" boolean;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "bathroom" varchar(50);--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "accept_waiting_list" boolean;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "scholarship_holders_priority" boolean;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "images_urls" text[];--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "external_url" varchar(255);--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "external_reference" varchar(255);--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "owner_id" bigint;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "target_audience" varchar(100);--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "created_at" timestamp;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" ADD COLUMN IF NOT EXISTS "updated_at" timestamp;--> statement-breakpoint
DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1
		FROM pg_constraint
		WHERE conname = 'accommodation_externalsource_accommodation_id_accommodation_accommodation_id_fk'
	) THEN
		ALTER TABLE "accommodation_externalsource"
		ADD CONSTRAINT "accommodation_externalsource_accommodation_id_accommodation_accommodation_id_fk"
		FOREIGN KEY ("accommodation_id")
		REFERENCES "public"."accommodation_accommodation"("id")
		ON DELETE no action
		ON UPDATE no action;
	END IF;
END
$$;--> statement-breakpoint
DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1
		FROM pg_constraint
		WHERE conname = 'accommodation_favoriteaccommodation_accommodation_id_accommodation_accommodation_id_fk'
	) THEN
		ALTER TABLE "accommodation_favoriteaccommodation"
		ADD CONSTRAINT "accommodation_favoriteaccommodation_accommodation_id_accommodation_accommodation_id_fk"
		FOREIGN KEY ("accommodation_id")
		REFERENCES "public"."accommodation_accommodation"("id")
		ON DELETE no action
		ON UPDATE no action;
	END IF;
END
$$;--> statement-breakpoint
DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1
		FROM pg_constraint
		WHERE conname = 'accommodation_accommodation_owner_id_account_owner_id_fk'
	) THEN
		ALTER TABLE "accommodation_accommodation"
		ADD CONSTRAINT "accommodation_accommodation_owner_id_account_owner_id_fk"
		FOREIGN KEY ("owner_id")
		REFERENCES "public"."account_owner"("id")
		ON DELETE no action
		ON UPDATE no action;
	END IF;
END
$$;
