CREATE TABLE "student_alert" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "student_alert_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"city_id" bigint,
	"department_id" bigint,
	"academy_id" bigint,
	"has_coliving" boolean DEFAULT false NOT NULL,
	"is_accessible" boolean DEFAULT false NOT NULL,
	"max_price" integer NOT NULL,
	"receive_notifications" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "student_alert" ADD CONSTRAINT "student_alert_city_id_territories_city_id_fk" FOREIGN KEY ("city_id") REFERENCES "public"."territories_city"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_alert" ADD CONSTRAINT "student_alert_department_id_territories_department_id_fk" FOREIGN KEY ("department_id") REFERENCES "public"."territories_department"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_alert" ADD CONSTRAINT "student_alert_academy_id_territories_academy_id_fk" FOREIGN KEY ("academy_id") REFERENCES "public"."territories_academy"("id") ON DELETE no action ON UPDATE no action;
