DROP TABLE IF EXISTS "stats_stats";--> statement-breakpoint
DROP TABLE IF EXISTS "stats_eventstats";--> statement-breakpoint
CREATE TABLE "stats_stats" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stats_stats_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"date" date NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"unique_visitors" integer,
	"new_visits_percentage" double precision,
	"average_duration" double precision,
	"bounce_rate_percentage" double precision,
	"page_views" integer,
	"visitors_per_page" double precision,
	"top_pages" jsonb,
	"main_entry_pages" jsonb,
	"main_sources" jsonb,
	CONSTRAINT "stats_stats_date_unique" UNIQUE("date")
);--> statement-breakpoint
CREATE TABLE "stats_eventstats" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stats_eventstats_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"date" date NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"category" varchar(255) NOT NULL,
	"action" varchar(255) NOT NULL,
	"nb_events" integer,
	"nb_unique_events" integer,
	"event_value" double precision
);
