CREATE TABLE "admin_owner_link" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "admin_owner_link_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"owner_id" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "admin_owner_link" ADD CONSTRAINT "admin_owner_link_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "admin_owner_link" ADD CONSTRAINT "admin_owner_link_owner_id_account_owner_id_fk" FOREIGN KEY ("owner_id") REFERENCES "public"."account_owner"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "admin_owner_link_user_owner_idx" ON "admin_owner_link" USING btree ("user_id","owner_id");--> statement-breakpoint
CREATE INDEX "admin_owner_link_user_id_idx" ON "admin_owner_link" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "admin_owner_link_owner_id_idx" ON "admin_owner_link" USING btree ("owner_id");