DROP TABLE IF EXISTS "stats_stats";--> statement-breakpoint
DROP TABLE IF EXISTS "stats_eventstats";--> statement-breakpoint

CREATE TABLE "stats" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "date" date NOT NULL UNIQUE,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "unique_visitors" integer,
  "new_visits_percentage" double precision,
  "average_duration" double precision,
  "bounce_rate_percentage" double precision,
  "page_views" integer,
  "visitors_per_page" double precision,
  "top_pages" jsonb,
  "main_entry_pages" jsonb,
  "main_sources" jsonb
);--> statement-breakpoint

CREATE TABLE "event_stats" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "date" date NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "category" varchar(255) NOT NULL,
  "action" varchar(255) NOT NULL,
  "nb_events" integer,
  "nb_unique_events" integer,
  "event_value" double precision
);
