CREATE TABLE "activity_log" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "user_id" text,
  "user_name" varchar(255),
  "action" varchar(100) NOT NULL,
  "entity_type" varchar(50) NOT NULL,
  "entity_id" varchar(255),
  "entity_name" varchar(255),
  "owner_id" bigint,
  "owner_name" varchar(255),
  "metadata" jsonb
);--> statement-breakpoint
CREATE INDEX "activity_log_owner_id_idx" ON "activity_log" ("owner_id");--> statement-breakpoint
CREATE INDEX "activity_log_created_at_idx" ON "activity_log" ("created_at");--> statement-breakpoint
CREATE INDEX "activity_log_action_idx" ON "activity_log" ("action");
