CREATE TABLE "accommodation_importblocklist" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"source" varchar(100) NOT NULL,
	"source_id" varchar(100) NOT NULL,
	"reason" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "accommodation_importblocklist_source_source_id_unique" UNIQUE("source","source_id")
);
