CREATE TABLE "accommodation_address" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "accommodation_id" bigint NOT NULL REFERENCES "accommodation_accommodation"("id") ON DELETE CASCADE,
  "is_main" boolean NOT NULL DEFAULT false,
  "address" varchar(255),
  "postal_code" varchar(5) NOT NULL,
  "city_id" bigint REFERENCES "territories_city"("id"),
  "geom" geometry(point, 4326)
);--> statement-breakpoint
CREATE INDEX "accommodation_address_accommodation_id_idx" ON "accommodation_address" ("accommodation_id");--> statement-breakpoint
CREATE INDEX "accommodation_address_city_id_idx" ON "accommodation_address" ("city_id");--> statement-breakpoint
CREATE INDEX "accommodation_address_geom_idx" ON "accommodation_address" USING GIST ("geom");--> statement-breakpoint
CREATE UNIQUE INDEX "accommodation_address_unique_main" ON "accommodation_address" ("accommodation_id") WHERE is_main = true;--> statement-breakpoint
INSERT INTO accommodation_address (accommodation_id, is_main, address, postal_code, city_id, geom)
SELECT id, true, address, postal_code, city_id, geom
FROM accommodation_accommodation
WHERE postal_code IS NOT NULL;--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" DROP COLUMN "address";--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" DROP COLUMN "postal_code";--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" DROP COLUMN "city_id";--> statement-breakpoint
ALTER TABLE "accommodation_accommodation" DROP COLUMN "geom";--> statement-breakpoint
DROP INDEX IF EXISTS "accommodation_city_id_idx";
