CREATE TABLE "tracking_event" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tracking_event_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"type" varchar(50) NOT NULL,
	"city_id" bigint,
	"department_id" bigint,
	"accommodation_id" bigint,
	"owner_id" bigint,
	"user_id" text,
	"session_id" varchar(64),
	"metadata" jsonb
);
--> statement-breakpoint
ALTER TABLE "tracking_event" ADD CONSTRAINT "tracking_event_city_id_territories_city_id_fk" FOREIGN KEY ("city_id") REFERENCES "public"."territories_city"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tracking_event" ADD CONSTRAINT "tracking_event_department_id_territories_department_id_fk" FOREIGN KEY ("department_id") REFERENCES "public"."territories_department"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tracking_event" ADD CONSTRAINT "tracking_event_accommodation_id_accommodation_accommodation_id_fk" FOREIGN KEY ("accommodation_id") REFERENCES "public"."accommodation_accommodation"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tracking_event" ADD CONSTRAINT "tracking_event_owner_id_account_owner_id_fk" FOREIGN KEY ("owner_id") REFERENCES "public"."account_owner"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tracking_event" ADD CONSTRAINT "tracking_event_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "tracking_event_type_created_idx" ON "tracking_event" USING btree ("type","created_at");--> statement-breakpoint
CREATE INDEX "tracking_event_city_created_idx" ON "tracking_event" USING btree ("city_id","created_at");--> statement-breakpoint
CREATE INDEX "tracking_event_department_created_idx" ON "tracking_event" USING btree ("department_id","created_at");--> statement-breakpoint
CREATE INDEX "tracking_event_accommodation_created_idx" ON "tracking_event" USING btree ("accommodation_id","created_at");--> statement-breakpoint
CREATE INDEX "tracking_event_owner_created_idx" ON "tracking_event" USING btree ("owner_id","created_at");--> statement-breakpoint
CREATE INDEX "tracking_event_session_created_idx" ON "tracking_event" USING btree ("session_id","created_at");