CREATE TYPE "public"."login_attempt_status" AS ENUM('email_sent', 'completed', 'expired', 'invalid');--> statement-breakpoint
CREATE TABLE "login_attempt" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "login_attempt_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"email" varchar(255),
	"user_id" text,
	"owner_id" bigint,
	"role" varchar(20),
	"token_hash" varchar(64) NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"status" "login_attempt_status" DEFAULT 'email_sent' NOT NULL,
	"verified_at" timestamp with time zone,
	"verified_user_agent" text,
	CONSTRAINT "login_attempt_token_hash_unique" UNIQUE("token_hash")
);
--> statement-breakpoint
ALTER TABLE "login_attempt" ADD CONSTRAINT "login_attempt_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "login_attempt" ADD CONSTRAINT "login_attempt_owner_id_owner_id_fk" FOREIGN KEY ("owner_id") REFERENCES "public"."owner"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "login_attempt_created_at_idx" ON "login_attempt" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "login_attempt_owner_id_idx" ON "login_attempt" USING btree ("owner_id");--> statement-breakpoint
CREATE INDEX "login_attempt_status_idx" ON "login_attempt" USING btree ("status");