CREATE TABLE "bailleur_accommodation_scope" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bailleur_accommodation_scope_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"accommodation_id" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "user" ADD COLUMN "application_scope_restricted" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "bailleur_accommodation_scope" ADD CONSTRAINT "bailleur_accommodation_scope_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bailleur_accommodation_scope" ADD CONSTRAINT "bailleur_accommodation_scope_accommodation_id_accommodation_id_fk" FOREIGN KEY ("accommodation_id") REFERENCES "public"."accommodation"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "bailleur_accommodation_scope_user_accommodation_idx" ON "bailleur_accommodation_scope" USING btree ("user_id","accommodation_id");--> statement-breakpoint
CREATE INDEX "bailleur_accommodation_scope_user_id_idx" ON "bailleur_accommodation_scope" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "bailleur_accommodation_scope_accommodation_id_idx" ON "bailleur_accommodation_scope" USING btree ("accommodation_id");--> statement-breakpoint
CREATE INDEX "dossier_facile_application_accommodation_slug_idx" ON "dossier_facile_application" USING btree ("accommodation_slug");