CREATE TYPE "public"."student_goal_due_delay" AS ENUM('one_week', 'two_weeks', 'one_month');--> statement-breakpoint
CREATE TABLE "student_goal_list" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "student_goal_list_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"email_reminders_enabled" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "student_goal" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "student_goal_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"list_id" bigint NOT NULL,
	"title" varchar(255) NOT NULL,
	"due_delay" "student_goal_due_delay" NOT NULL,
	"due_at" timestamp with time zone NOT NULL,
	"position" integer DEFAULT 0 NOT NULL,
	"completed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "student_goal_list" ADD CONSTRAINT "student_goal_list_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_goal" ADD CONSTRAINT "student_goal_list_id_student_goal_list_id_fk" FOREIGN KEY ("list_id") REFERENCES "public"."student_goal_list"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "student_goal_list_user_id_idx" ON "student_goal_list" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "student_goal_list_id_idx" ON "student_goal" USING btree ("list_id");