export const EQUIPMENTS = [
  {
    icon: 'ri-fridge-line',
    key: 'refrigerator',
    label: 'Frigo',
    category: 'individual',
  },
  {
    icon: 'ri-t-shirt-air-line',
    key: 'laundry_room',
    label: 'Laverie',
    category: 'collective',
  },
  {
    icon: 'ri-bubble-chart-line',
    key: 'bathroom',
    label: (value: string) => (value === 'private' ? 'Salle de bain privée' : 'Salle de bain partagée'),
    category: 'individual',
  },
  {
    icon: 'ri-restaurant-line',
    key: 'kitchen_type',
    label: (value: string) => (value === 'private' ? 'Cuisine privée' : 'Cuisine partagée'),
    category: 'individual',
  },
  {
    icon: 'ri-bowl-line',
    key: 'microwave',
    label: 'Micro-onde',
    category: 'individual',
  },
  {
    icon: 'ri-lock-line',
    key: 'secure_access',
    label: 'Accès sécurisé',
    category: 'collective',
  },
  {
    icon: 'ri-parking-box-line',
    key: 'parking',
    label: 'Parking',
    category: 'collective',
  },
  {
    icon: 'ri-community-line',
    key: 'common_areas',
    label: 'Espaces communs',
    category: 'collective',
  },
  {
    icon: 'ri-riding-line',
    key: 'bike_storage',
    label: 'Garage à vélos',
    category: 'collective',
  },
  {
    icon: 'ri-ball-pen-line',
    key: 'desk',
    label: 'Bureau',
    category: 'individual',
  },
  {
    icon: 'ri-user-2-line',
    key: 'residence_manager',
    label: 'Conciergerie',
    category: 'collective',
  },
  {
    icon: 'fr-icon-sign-language-line',
    key: 'cooking_plates',
    label: 'Plaques de cuisson',
    category: 'individual',
  },
  {
    icon: 'ri-wifi-line',
    key: 'wifi',
    label: 'Wifi',
    category: 'collective',
  },
]
